name: Sanity Test CI

on:
    pull_request:
          branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 black pytest matplotlib scikit-learn joblib pandas

      - name: Run training script
        run: python src/train.py

      - name: Check code formatting (black)
        run: black --check .

      - name: Lint with flake8
        run: flake8 .

      - name: Run unit tests
        run: pytest tests/

      - name: Plot performance metrics
        run: python src/plot_metrics.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: |
            model.joblib
            label_encoder.joblib
            test_data.joblib
            metrics.png
            report.md

      - name: Setup CML
        uses: iterative/setup-cml@v2


      - name: Comment report on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create report.md
